### ISSUE TITLE
Gra w zgadywanie liczby z przedziału od 1-100 

### ISSUE THREAD

**Issue by Xarvius** [Xarvius/TIL#1]
> Idea bardzo prosta - program ma za zadanie wylosować liczbę, a użytkownik ma ją zgadnąć. Jeśli użytkownik poda mniejszą niż wylosowana - program wypisuje tekst "za mała liczba", jeśli poda większą wypisuje "za duża liczba".
> 
> Przykładowy przebieg programu:
> 
> ```
> Została wylosowana liczba z przedziały 1-100. 
> Zgadnij jaka to liczba: 40 <enter>
> Za duża liczba.
> Zgadnij jeszcze raz: 33<enter>
> Za mała liczba. 
> Zgadnij jeszcze raz: 35<enter>
> Za duża liczba. 
> Zgadnij jeszcze raz: 34<enter>
> Tak! Brawo!
> ```

**Comment by Xarvius** [comment]
Czy powinienem zrobić to przy pomocy while, czy może być funkcja?

**Comment by noisy** [comment]
Czy funkcje będziesz miał czy nie, to jakiejś pętli będziesz potrzebował. Istnieją 3 rodzaje pętli. for, while i do-while. Python pętli do-while nie posiada, wiec zostają do wyboru for i while.

for zazwyczaj się stosuje do iterowania po znanej liczbie elementów, gdzie while zazwyczaj stosuje się tam, gdzie nie wiemy jak długo przyjdzie nam czekać na spełnienie warunku który zatrzyma pętle.

**Comment by noisy** [comment]
done: https://github.com/Xarvius/TIL/pull/8
